# Generated by Django 2.0.13 on 2019-06-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polocApp', '0002_cliente_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaNecesidad', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('archivosAdjuntos', models.FileField(upload_to='adjuntos')),
                ('criticidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polocApp.Criticidad')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polocApp.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'solicitudes de mantenimiento',
                'verbose_name': 'solicitud de mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'tipos de solicitud',
                'verbose_name': 'tipo de solicitud',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='proyecto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polocApp.Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudmantenimiento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polocApp.TipoSolicitud'),
        ),
    ]
